# Path to the directory storing genomes is writen in local config file (config_local.yaml)
genomes: ""

skani:
    threads: 16

ani_distribution_plot:
    floor: 95
    mad_k: 5
    min_drop: 0.5

parsnp:
    threads: 8

reference_genomes:
    db_dir: "../../databases"

sourmash:
    k: 31
    scale: 1000