# Path to the directory storing genomes is writen in local config file (config_local.yaml)
genomes: ""

# QC parameters
skani:
    threads: 16

ani_distribution_plot:
    floor: 95
    mad_k: 5
    min_drop: 0.5

# parsnp is used both in QC and main workflow
parsnp:
    threads: 16

# Main workflow parameters
reference_genomes:
    db_dir: "../../databases"

sourmash:
    k: 31
    scale: 1000
    similarity: 0.9

ncbi:
    data_top: 50
    contig_n: 5

gubbins:
    threads: 16

sliding_window:
    window: 2000
    threshold: 3

snp_from_tree:
    threshold: 1
